### ISSUE TITLE
async-upload doesn't work on 10-aws-syd

### ISSUE THREAD

**Issue by mhidas** [aodn/chef#366]
The `asynd-upload.py` script allows us to bulk upload a bunch of files directly to S3 without indexing (see #265 ). It used to work fine, and still does on 14-nsp-mel (uploading to the *imos-test-data* bucket), but I tried to use it on 10-aws-syd last week and nothing has been uploaded. No error messages are printed. Maybe these uploads are being added to a queue, but they are not being processed.

There's also no easy way to check what this command is doing (https://github.com/aodn/internal-discussions/issues/260)

**Comment by lwgordonimos** [comment]
@mhidas Looking now...

**Comment by mhidas** [comment]
@pblain

**Comment by mhidas** [comment]
Thanks @lwgordonimos!
I think the conclusion was that my uploads were failing because the projectofficer user (or is it root?) had no read access to the files I was trying to upload.
In any case, having an easily accessible error log at /mnt/ebs/log/data-services/async_upload.log will be very handy in the future.

Will that log get rotated daily? Or deleted?

**Comment by lwgordonimos** [comment]
@mhidas The logging is still the default values, which looks to clean them up whenever the supervisor daemon is restarted.

**Comment by mhidas** [comment]
How often does that happen?

**Comment by lwgordonimos** [comment]
For example, the current logs go back three weeks, but we should probably be more explicit to have a predictable retention period at least for this log, since it's the only record that this command has been run (other than the existence or absence of the files in S3)!

**Comment by mhidas** [comment]
Yes, let's do that!

**Comment by lwgordonimos** [comment]
@mhidas FYI, there are two PRs which will prevent the logs being clobbered on every service restart, and moved them to the data services logging area as well.

Accordingly, I've reduced the retention a bit on the 'normal' automatic queues (as opposed to the interactive async_upload) to prevent too much storage wastage, since the 'nocleanup' option is global to supervisord and not able to be set per-queue.

https://github.com/aodn/chef/pull/377
https://github.com/aodn/chef-private/pull/2011

**Comment by mhidas** [comment]
Cool, thanks!
